name: Build and Tag Docker Image
on:
  push:
     tags:
       - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v4

       - name: Setup go
         uses: actions/setup-go@v5
         with:
           go-version: '1.21'

       - name: Display Go version
         run: go version
         
       - name: Run Go tests
         run: go test ./...
         continue-on-error: true

       - name: Build and tag Docker Image
         run: |
           TAG_NAME=${GITHUB_REF##*/}
           if [[ ! "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Not a semver tag (vX.Y.Z). Skipping docker tag."
            exit 0
           fi           
           SHORT_SHA=$(git rev-parse --short HEAD)
           BUILD_DATE=$(date +%Y%m%d%H%M%S)
           IMAGE_TAG=${TAG_NAME}-${BUILD_DATE}-${SHORT_SHA}

           echo "Building Go App Docker image: my-go-app:$IMAGE_TAG"
           docker build -t my-go-app:$IMAGE_TAG 
           echo "Docker image built and tagged as: my-go-app:$IMAGE_TAG"
        
     
