name: Build and Tag Docker Image
on:
  push:
     tags:
       - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v4

       - name: Setup go
         uses: actions/setup-go@v5
         with:
           go-version: '1.21'

       - name: Run Go tests
         run: go test ./...

       - name: Build and tag Docker Image
         run: |
           TAG_NAME=${GITHUB_REF##*/}
           SHORT_SHA=$(git rev-parse --short HEAD)
           BUILD_DATE=$(date +%Y%m%d%H%M%S)
           IMAGE_TAG=${TAG_NAME}-${BUILD_DATE}-${SHORT_SHA}

           echo "Building image: nginx:$IMAGE_TAG"
           docker pull nginx:latest
           docker tag nginx:latest nginx:$IMAGE_NAME
           echo "Tagged nginx image as: nginx:$IMAGE_TAG"
        
     
